export const countries = [
  {
    name: "Brasil",
    code: "BR",
    altCode: "BRA",
    numberCode: "076",
  },
  {
    name: "Afeganistão",
    code: "AF",
    altCode: "AFG",
    numberCode: "004",
  },
  {
    name: "África do Sul",
    code: "ZA",
    altCode: "ZAF",
    numberCode: "710",
  },
  {
    name: "Albânia",
    code: "AL",
    altCode: "ALB",
    numberCode: "008",
  },
  {
    name: "Alemanha",
    code: "DE",
    altCode: "DEU",
    numberCode: "276",
  },
  {
    name: "Andorra",
    code: "AD",
    altCode: "AND",
    numberCode: "020",
  },
  {
    name: "Angola",
    code: "AO",
    altCode: "AGO",
    numberCode: "024",
  },
  {
    name: "Anguilla",
    code: "AI",
    altCode: "AIA",
    numberCode: "660",
  },
  {
    name: "Antártida",
    code: "AQ",
    altCode: "ATA",
    numberCode: "010",
  },
  {
    name: "Antígua e Barbuda",
    code: "AG",
    altCode: "ATG",
    numberCode: "028",
  },
  {
    name: "Antilhas Holandesas",
    code: "AN",
    altCode: "ANT",
    numberCode: "530",
  },
  {
    name: "Arábia Saudita",
    code: "SA",
    altCode: "SAU",
    numberCode: "682",
  },
  {
    name: "Argélia",
    code: "DZ",
    altCode: "DZA",
    numberCode: "012",
  },
  {
    name: "Argentina",
    code: "AR",
    altCode: "ARG",
    numberCode: "032",
  },
  {
    name: "Armênia",
    code: "AM",
    altCode: "ARM",
    numberCode: "51",
  },
  {
    name: "Aruba",
    code: "AW",
    altCode: "ABW",
    numberCode: "533",
  },
  {
    name: "Austrália",
    code: "AU",
    altCode: "AUS",
    numberCode: "036",
  },
  {
    name: "Áustria",
    code: "AT",
    altCode: "AUT",
    numberCode: "040",
  },
  {
    name: "Azerbaijão",
    code: "AZ  ",
    altCode: "AZE",
    numberCode: "31",
  },
  {
    name: "Bahamas",
    code: "BS",
    altCode: "BHS",
    numberCode: "044",
  },
  {
    name: "Bahrein",
    code: "BH",
    altCode: "BHR",
    numberCode: "048",
  },
  {
    name: "Bangladesh",
    code: "BD",
    altCode: "BGD",
    numberCode: "050",
  },
  {
    name: "Barbados",
    code: "BB",
    altCode: "BRB",
    numberCode: "052",
  },
  {
    name: "Belarus",
    code: "BY",
    altCode: "BLR",
    numberCode: "112",
  },
  {
    name: "Bélgica",
    code: "BE",
    altCode: "BEL",
    numberCode: "056",
  },
  {
    name: "Belize",
    code: "BZ",
    altCode: "BLZ",
    numberCode: "084",
  },
  {
    name: "Benin",
    code: "BJ",
    altCode: "BEN",
    numberCode: "204",
  },
  {
    name: "Bermudas",
    code: "BM",
    altCode: "BMU",
    numberCode: "060",
  },
  {
    name: "Bolívia",
    code: "BO",
    altCode: "BOL",
    numberCode: "068",
  },
  {
    name: "Bósnia-Herzegóvina",
    code: "BA",
    altCode: "BIH",
    numberCode: "070",
  },
  {
    name: "Botsuana",
    code: "BW",
    altCode: "BWA",
    numberCode: "072",
  },
  {
    name: "Brunei",
    code: "BN",
    altCode: "BRN",
    numberCode: "096",
  },
  {
    name: "Bulgária",
    code: "BG",
    altCode: "BGR",
    numberCode: "100",
  },
  {
    name: "Burkina Fasso",
    code: "BF",
    altCode: "BFA",
    numberCode: "854",
  },
  {
    name: "Burundi",
    code: "BI",
    altCode: "BDI",
    numberCode: "108",
  },
  {
    name: "Butão",
    code: "BT",
    altCode: "BTN",
    numberCode: "064",
  },
  {
    name: "Cabo Verde",
    code: "CV",
    altCode: "CPV",
    numberCode: "132",
  },
  {
    name: "Camarões",
    code: "CM",
    altCode: "CMR",
    numberCode: "120",
  },
  {
    name: "Camboja",
    code: "KH",
    altCode: "KHM",
    numberCode: "116",
  },
  {
    name: "Canadá",
    code: "CA",
    altCode: "CAN",
    numberCode: "124",
  },
  {
    name: "Cazaquistão",
    code: "KZ",
    altCode: "KAZ",
    numberCode: "398",
  },
  {
    name: "Chade",
    code: "TD",
    altCode: "TCD",
    numberCode: "148",
  },
  {
    name: "Chile",
    code: "CL",
    altCode: "CHL",
    numberCode: "152",
  },
  {
    name: "China",
    code: "CN",
    altCode: "CHN",
    numberCode: "156",
  },
  {
    name: "Chipre",
    code: "CY",
    altCode: "CYP",
    numberCode: "196",
  },
  {
    name: "Cingapura",
    code: "SG",
    altCode: "SGP",
    numberCode: "702",
  },
  {
    name: "Colômbia",
    code: "CO",
    altCode: "COL",
    numberCode: "170",
  },
  {
    name: "Congo",
    code: "CG",
    altCode: "COG",
    numberCode: "178",
  },
  {
    name: "Coréia do Norte",
    code: "KP",
    altCode: "PRK",
    numberCode: "408",
  },
  {
    name: "Coréia do Sul",
    code: "KR",
    altCode: "KOR",
    numberCode: "410",
  },
  {
    name: "Costa do Marfim",
    code: "CI",
    altCode: "CIV",
    numberCode: "384",
  },
  {
    name: "Costa Rica",
    code: "CR",
    altCode: "CRI",
    numberCode: "188",
  },
  {
    name: "Croácia (Hrvatska)",
    code: "HR",
    altCode: "HRV",
    numberCode: "191",
  },
  {
    name: "Cuba",
    code: "CU",
    altCode: "CUB",
    numberCode: "192",
  },
  {
    name: "Dinamarca",
    code: "DK",
    altCode: "DNK",
    numberCode: "208",
  },
  {
    name: "Djibuti",
    code: "DJ",
    altCode: "DJI",
    numberCode: "262",
  },
  {
    name: "Dominica",
    code: "DM",
    altCode: "DMA",
    numberCode: "212",
  },
  {
    name: "Egito",
    code: "EG",
    altCode: "EGY",
    numberCode: "818",
  },
  {
    name: "El Salvador",
    code: "SV",
    altCode: "SLV",
    numberCode: "222",
  },
  {
    name: "Emirados Árabes Unidos",
    code: "AE",
    altCode: "ARE",
    numberCode: "784",
  },
  {
    name: "Equador",
    code: "EC",
    altCode: "ECU",
    numberCode: "218",
  },
  {
    name: "Eritréia",
    code: "ER",
    altCode: "ERI",
    numberCode: "232",
  },
  {
    name: "Eslováquia",
    code: "SK",
    altCode: "SVK",
    numberCode: "703",
  },
  {
    name: "Eslovênia",
    code: "SI",
    altCode: "SVN",
    numberCode: "705",
  },
  {
    name: "Espanha",
    code: "ES",
    altCode: "ESP",
    numberCode: "724",
  },
  {
    name: "Estados Unidos",
    code: "US",
    altCode: "USA",
    numberCode: "840",
  },
  {
    name: "Estônia",
    code: "EE",
    altCode: "EST",
    numberCode: "233",
  },
  {
    name: "Etiópia",
    code: "ET",
    altCode: "ETH",
    numberCode: "231",
  },
  {
    name: "Fiji",
    code: "FJ",
    altCode: "FJI",
    numberCode: "242",
  },
  {
    name: "Filipinas",
    code: "PH",
    altCode: "PHL",
    numberCode: "608",
  },
  {
    name: "Finlândia",
    code: "FI",
    altCode: "FIN",
    numberCode: "246",
  },
  {
    name: "França",
    code: "FR",
    altCode: "FRA",
    numberCode: "250",
  },
  {
    name: "Gabão",
    code: "GA",
    altCode: "GAB",
    numberCode: "266",
  },
  {
    name: "Gâmbia",
    code: "GM",
    altCode: "GMB",
    numberCode: "270",
  },
  {
    name: "Gana",
    code: "GH",
    altCode: "GHA",
    numberCode: "288",
  },
  {
    name: "Geórgia",
    code: "GE",
    altCode: "GEO",
    numberCode: "268",
  },
  {
    name: "Gibraltar",
    code: "GI",
    altCode: "GIB",
    numberCode: "292",
  },
  {
    name: "Grã-Bretanha (Reino Unido, UK)",
    code: "GB",
    altCode: "GBR",
    numberCode: "826",
  },
  {
    name: "Granada",
    code: "GD",
    altCode: "GRD",
    numberCode: "308",
  },
  {
    name: "Grécia",
    code: "GR",
    altCode: "GRC",
    numberCode: "300",
  },
  {
    name: "Groelândia",
    code: "GL",
    altCode: "GRL",
    numberCode: "304",
  },
  {
    name: "Guadalupe",
    code: "GP",
    altCode: "GLP",
    numberCode: "312",
  },
  {
    name: "Guam (Território dos Estados Unidos)",
    code: "GU",
    altCode: "GUM",
    numberCode: "316",
  },
  {
    name: "Guatemala",
    code: "GT",
    altCode: "GTM",
    numberCode: "320",
  },
  {
    name: "Guernsey",
    code: "G",
    altCode: "GGY",
    numberCode: "832",
  },
  {
    name: "Guiana",
    code: "GY",
    altCode: "GUY",
    numberCode: "328",
  },
  {
    name: "Guiana Francesa",
    code: "GF",
    altCode: "GUF",
    numberCode: "254",
  },
  {
    name: "Guiné",
    code: "GN",
    altCode: "GIN",
    numberCode: "324",
  },
  {
    name: "Guiné Equatorial",
    code: "GQ",
    altCode: "GNQ",
    numberCode: "226",
  },
  {
    name: "Guiné-Bissau",
    code: "GW",
    altCode: "GNB",
    numberCode: "624",
  },
  {
    name: "Haiti",
    code: "HT",
    altCode: "HTI",
    numberCode: "332",
  },
  {
    name: "Holanda",
    code: "NL",
    altCode: "NLD",
    numberCode: "528",
  },
  {
    name: "Honduras",
    code: "HN",
    altCode: "HND",
    numberCode: "340",
  },
  {
    name: "Hong Kong",
    code: "HK",
    altCode: "HKG",
    numberCode: "344",
  },
  {
    name: "Hungria",
    code: "HU",
    altCode: "HUN",
    numberCode: "348",
  },
  {
    name: "Iêmen",
    code: "YE",
    altCode: "YEM",
    numberCode: "887",
  },
  {
    name: "Ilha Bouvet (Território da Noruega)",
    code: "BV",
    altCode: "BVT",
    numberCode: "074",
  },
  {
    name: "Ilha do Homem",
    code: "IM",
    altCode: "IMN",
    numberCode: "833",
  },
  {
    name: "Ilha Natal",
    code: "CX",
    altCode: "CXR",
    numberCode: "162",
  },
  {
    name: "Ilha Pitcairn",
    code: "PN",
    altCode: "PCN",
    numberCode: "612",
  },
  {
    name: "Ilha Reunião",
    code: "RE",
    altCode: "REU",
    numberCode: "638",
  },
  {
    name: "Ilhas Aland",
    code: "AX",
    altCode: "ALA",
    numberCode: "248",
  },
  {
    name: "Ilhas Cayman",
    code: "KY",
    altCode: "CYM",
    numberCode: "136",
  },
  {
    name: "Ilhas Cocos",
    code: "CC",
    altCode: "CCK",
    numberCode: "166",
  },
  {
    name: "Ilhas Comores",
    code: "KM",
    altCode: "COM",
    numberCode: "174",
  },
  {
    name: "Ilhas Cook",
    code: "CK",
    altCode: "COK",
    numberCode: "184",
  },
  {
    name: "Ilhas Faroes",
    code: "FO",
    altCode: "FRO",
    numberCode: "234",
  },
  {
    name: "Ilhas Falkland (Malvinas)",
    code: "FK",
    altCode: "FLK",
    numberCode: "238",
  },
  {
    name: "Ilhas Geórgia do Sul e Sandwich do Sul",
    code: "GS",
    altCode: "SGS",
    numberCode: "239",
  },
  {
    name: "Ilhas Heard e McDonald (Território da Austrália)",
    code: "HM",
    altCode: "HMD",
    numberCode: "334",
  },
  {
    name: "Ilhas Marianas do Norte",
    code: "MP",
    altCode: "MNP",
    numberCode: "580",
  },
  {
    name: "Ilhas Marshall",
    code: "MH",
    altCode: "MHL",
    numberCode: "584",
  },
  {
    name: "Ilhas Menores dos Estados Unidos",
    code: "UM",
    altCode: "UMI",
    numberCode: "581",
  },
  {
    name: "Ilhas Norfolk",
    code: "NF",
    altCode: "NFK",
    numberCode: "574",
  },
  {
    name: "Ilhas Seychelles",
    code: "SC",
    altCode: "SYC",
    numberCode: "690",
  },
  {
    name: "Ilhas Solomão",
    code: "SB",
    altCode: "SLB",
    numberCode: "090",
  },
  {
    name: "Ilhas Svalbard e Jan Mayen",
    code: "SJ",
    altCode: "SJM",
    numberCode: "744",
  },
  {
    name: "Ilhas Tokelau",
    code: "TK",
    altCode: "TKL",
    numberCode: "772",
  },
  {
    name: "Ilhas Turks e Caicos",
    code: "TC",
    altCode: "TCA",
    numberCode: "796",
  },
  {
    name: "Ilhas Virgens (Estados Unidos)",
    code: "VI",
    altCode: "VIR",
    numberCode: "850",
  },
  {
    name: "Ilhas Virgens (Inglaterra)",
    code: "VG",
    altCode: "VGB",
    numberCode: "092",
  },
  {
    name: "Ilhas Wallis e Futuna",
    code: "WF",
    altCode: "WLF",
    numberCode: "876",
  },
  {
    name: "índia",
    code: "IN",
    altCode: "IND",
    numberCode: "356",
  },
  {
    name: "Indonésia",
    code: "ID",
    altCode: "IDN",
    numberCode: "360",
  },
  {
    name: "Irã",
    code: "IR",
    altCode: "IRN",
    numberCode: "364",
  },
  {
    name: "Iraque",
    code: "IQ",
    altCode: "IRQ",
    numberCode: "368",
  },
  {
    name: "Irlanda",
    code: "IE",
    altCode: "IRL",
    numberCode: "372",
  },
  {
    name: "Islândia",
    code: "IS",
    altCode: "ISL",
    numberCode: "352",
  },
  {
    name: "Israel",
    code: "IL",
    altCode: "ISR",
    numberCode: "376",
  },
  {
    name: "Itália",
    code: "IT",
    altCode: "ITA",
    numberCode: "380",
  },
  {
    name: "Jamaica",
    code: "JM",
    altCode: "JAM",
    numberCode: "388",
  },
  {
    name: "Japão",
    code: "JP",
    altCode: "JPN",
    numberCode: "392",
  },
  {
    name: "Jersey",
    code: "JE",
    altCode: "JEY",
    numberCode: "832",
  },
  {
    name: "Jordânia",
    code: "JO",
    altCode: "JOR",
    numberCode: "400",
  },
  {
    name: "Kênia",
    code: "KE",
    altCode: "KEN",
    numberCode: "404",
  },
  {
    name: "Kiribati",
    code: "KI",
    altCode: "KIR",
    numberCode: "296",
  },
  {
    name: "Kuait",
    code: "KW",
    altCode: "KWT",
    numberCode: "414",
  },
  {
    name: "Laos",
    code: "LA",
    altCode: "LAO",
    numberCode: "418",
  },
  {
    name: "Látvia",
    code: "LV",
    altCode: "LVA",
    numberCode: "428",
  },
  {
    name: "Lesoto",
    code: "LS",
    altCode: "LSO",
    numberCode: "426",
  },
  {
    name: "Líbano",
    code: "LB",
    altCode: "LBN",
    numberCode: "422",
  },
  {
    name: "Libéria",
    code: "LR",
    altCode: "LBR",
    numberCode: "430",
  },
  {
    name: "Líbia",
    code: "LY",
    altCode: "LBY",
    numberCode: "434",
  },
  {
    name: "Liechtenstein",
    code: "LI",
    altCode: "LIE",
    numberCode: "438",
  },
  {
    name: "Lituânia",
    code: "LT",
    altCode: "LTU",
    numberCode: "440",
  },
  {
    name: "Luxemburgo",
    code: "LU",
    altCode: "LUX",
    numberCode: "442",
  },
  {
    name: "Macau",
    code: "MO",
    altCode: "MAC",
    numberCode: "446",
  },
  {
    name: "Macedônia (República Yugoslava)",
    code: "MK",
    altCode: "MKD",
    numberCode: "807",
  },
  {
    name: "Madagascar",
    code: "MG",
    altCode: "MDG",
    numberCode: "450",
  },
  {
    name: "Malásia",
    code: "MY",
    altCode: "MYS",
    numberCode: "458",
  },
  {
    name: "Malaui",
    code: "MW",
    altCode: "MWI",
    numberCode: "454",
  },
  {
    name: "Maldivas",
    code: "MV",
    altCode: "MDV",
    numberCode: "462",
  },
  {
    name: "Mali",
    code: "ML",
    altCode: "MLI",
    numberCode: "466",
  },
  {
    name: "Malta",
    code: "MT",
    altCode: "MLT",
    numberCode: "470",
  },
  {
    name: "Marrocos",
    code: "MA",
    altCode: "MAR",
    numberCode: "504",
  },
  {
    name: "Martinica",
    code: "MQ",
    altCode: "MTQ",
    numberCode: "474",
  },
  {
    name: "Maurício",
    code: "MU",
    altCode: "MUS",
    numberCode: "480",
  },
  {
    name: "Mauritânia",
    code: "MR",
    altCode: "MRT",
    numberCode: "478",
  },
  {
    name: "Mayotte",
    code: "YT",
    altCode: "MYT",
    numberCode: "175",
  },
  {
    name: "México",
    code: "MX",
    altCode: "MEX",
    numberCode: "484",
  },
  {
    name: "Micronésia",
    code: "FM",
    altCode: "FSM",
    numberCode: "583",
  },
  {
    name: "Moçambique",
    code: "MZ",
    altCode: "MOZ",
    numberCode: "508",
  },
  {
    name: "Moldova",
    code: "MD",
    altCode: "MDA",
    numberCode: "498",
  },
  {
    name: "Mônaco",
    code: "MC",
    altCode: "MCO",
    numberCode: "492",
  },
  {
    name: "Mongólia",
    code: "MN",
    altCode: "MNG",
    numberCode: "496",
  },
  {
    name: "Montenegro",
    code: "ME",
    altCode: "MNE",
    numberCode: "499",
  },
  {
    name: "Montserrat",
    code: "MS",
    altCode: "MSR",
    numberCode: "500",
  },
  {
    name: "Myanma",
    code: "MM",
    altCode: "MMR",
    numberCode: "104",
  },
  {
    name: "Namíbia",
    code: "NA",
    altCode: "NAM",
    numberCode: "516",
  },
  {
    name: "Nauru",
    code: "NR",
    altCode: "NRU",
    numberCode: "520",
  },
  {
    name: "Nepal",
    code: "NP",
    altCode: "NPL",
    numberCode: "524",
  },
  {
    name: "Nicarágua",
    code: "NI",
    altCode: "NIC",
    numberCode: "558",
  },
  {
    name: "Níger",
    code: "NE",
    altCode: "NER",
    numberCode: "562",
  },
  {
    name: "Nigéria",
    code: "NG",
    altCode: "NGA",
    numberCode: "566",
  },
  {
    name: "Niue",
    code: "NU",
    altCode: "NIU",
    numberCode: "570",
  },
  {
    name: "Noruega",
    code: "NO",
    altCode: "NOR",
    numberCode: "578",
  },
  {
    name: "Nova Caledônia",
    code: "NC",
    altCode: "NCL",
    numberCode: "540",
  },
  {
    name: "Nova Zelândia",
    code: "NZ",
    altCode: "NZL",
    numberCode: "554",
  },
  {
    name: "Omã",
    code: "OM",
    altCode: "OMN",
    numberCode: "512",
  },
  {
    name: "Palau",
    code: "PW",
    altCode: "PLW",
    numberCode: "585",
  },
  {
    name: "Panamá",
    code: "PA",
    altCode: "PAN",
    numberCode: "591",
  },
  {
    name: "Papua-Nova Guiné",
    code: "PG",
    altCode: "PNG",
    numberCode: "598",
  },
  {
    name: "Paquistão",
    code: "PK",
    altCode: "PAK",
    numberCode: "586",
  },
  {
    name: "Paraguai",
    code: "PY",
    altCode: "PRY",
    numberCode: "600",
  },
  {
    name: "Peru",
    code: "PE",
    altCode: "PER",
    numberCode: "604",
  },
  {
    name: "Polinésia Francesa",
    code: "PF",
    altCode: "PYF",
    numberCode: "258",
  },
  {
    name: "Polônia",
    code: "PL",
    altCode: "POL",
    numberCode: "616",
  },
  {
    name: "Porto Rico",
    code: "PR",
    altCode: "PRI",
    numberCode: "630",
  },
  {
    name: "Portugal",
    code: "PT",
    altCode: "PRT",
    numberCode: "620",
  },
  {
    name: "Qatar",
    code: "QA",
    altCode: "QAT",
    numberCode: "634",
  },
  {
    name: "Quirguistão",
    code: "KG",
    altCode: "KGZ",
    numberCode: "417",
  },
  {
    name: "República Centro-Africana",
    code: "CF",
    altCode: "CAF",
    numberCode: "140",
  },
  {
    name: "República Democrática do Congo",
    code: "CD",
    altCode: "COD",
    numberCode: "180",
  },
  {
    name: "República Dominicana",
    code: "DO",
    altCode: "DOM",
    numberCode: "214",
  },
  {
    name: "República Tcheca",
    code: "CZ",
    altCode: "CZE",
    numberCode: "203",
  },
  {
    name: "Romênia",
    code: "RO",
    altCode: "ROM",
    numberCode: "642",
  },
  {
    name: "Ruanda",
    code: "RW",
    altCode: "RWA",
    numberCode: "646",
  },
  {
    name: "Rússia (antiga URSS) - Federação Russa",
    code: "RU",
    altCode: "RUS",
    numberCode: "643",
  },
  {
    name: "Saara Ocidental",
    code: "EH",
    altCode: "ESH",
    numberCode: "732",
  },
  {
    name: "Saint Vincente e Granadinas",
    code: "VC",
    altCode: "VCT",
    numberCode: "670",
  },
  {
    name: "Samoa Americana",
    code: "AS",
    altCode: "ASM",
    numberCode: "016",
  },
  {
    name: "Samoa Ocidental",
    code: "WS",
    altCode: "WSM",
    numberCode: "882",
  },
  {
    name: "San Marino",
    code: "SM",
    altCode: "SMR",
    numberCode: "674",
  },
  {
    name: "Santa Helena",
    code: "SH",
    altCode: "SHN",
    numberCode: "654",
  },
  {
    name: "Santa Lúcia",
    code: "LC",
    altCode: "LCA",
    numberCode: "662",
  },
  {
    name: "São Bartolomeu",
    code: "BL",
    altCode: "BLM",
    numberCode: "652",
  },
  {
    name: "São Cristóvão e Névis",
    code: "KN",
    altCode: "KNA",
    numberCode: "659",
  },
  {
    name: "São Martim",
    code: "MF",
    altCode: "MAF",
    numberCode: "663",
  },
  {
    name: "São Tomé e Príncipe",
    code: "ST",
    altCode: "STP",
    numberCode: "678",
  },
  {
    name: "Senegal",
    code: "SN",
    altCode: "SEN",
    numberCode: "686",
  },
  {
    name: "Serra Leoa",
    code: "SL",
    altCode: "SLE",
    numberCode: "694",
  },
  {
    name: "Sérvia",
    code: "RS",
    altCode: "SRB",
    numberCode: "688",
  },
  {
    name: "Síria",
    code: "SY",
    altCode: "SYR",
    numberCode: "760",
  },
  {
    name: "Somália",
    code: "SO",
    altCode: "SOM",
    numberCode: "706",
  },
  {
    name: "Sri Lanka",
    code: "LK",
    altCode: "LKA",
    numberCode: "144",
  },
  {
    name: "St. Pierre and Miquelon",
    code: "PM",
    altCode: "SPM",
    numberCode: "666",
  },
  {
    name: "Suazilândia",
    code: "SZ",
    altCode: "SWZ",
    numberCode: "748",
  },
  {
    name: "Sudão",
    code: "SD",
    altCode: "SDN",
    numberCode: "736",
  },
  {
    name: "Suécia",
    code: "SE",
    altCode: "SWE",
    numberCode: "752",
  },
  {
    name: "Suíça",
    code: "CH",
    altCode: "CHE",
    numberCode: "756",
  },
  {
    name: "Suriname",
    code: "SR",
    altCode: "SUR",
    numberCode: "740",
  },
  {
    name: "Tadjiquistão",
    code: "TJ",
    altCode: "TJK",
    numberCode: "762",
  },
  {
    name: "Tailândia",
    code: "TH",
    altCode: "THA",
    numberCode: "764",
  },
  {
    name: "Taiwan",
    code: "TW",
    altCode: "TWN",
    numberCode: "158",
  },
  {
    name: "Tanzânia",
    code: "TZ",
    altCode: "TZA",
    numberCode: "834",
  },
  {
    name: "Território Britânico do Oceano índico",
    code: "IO",
    altCode: "IOT",
    numberCode: "086",
  },
  {
    name: "Territórios do Sul da França",
    code: "TF",
    altCode: "ATF",
    numberCode: "260",
  },
  {
    name: "Territórios Palestinos Ocupados",
    code: "PS",
    altCode: "PSE",
    numberCode: "275",
  },
  {
    name: "Timor Leste",
    code: "TP",
    altCode: "TMP",
    numberCode: "626",
  },
  {
    name: "Togo",
    code: "TG",
    altCode: "TGO",
    numberCode: "768",
  },
  {
    name: "Tonga",
    code: "TO",
    altCode: "TON",
    numberCode: "776",
  },
  {
    name: "Trinidad and Tobago",
    code: "TT",
    altCode: "TTO",
    numberCode: "780",
  },
  {
    name: "Tunísia",
    code: "TN",
    altCode: "TUN",
    numberCode: "788",
  },
  {
    name: "Turcomenistão",
    code: "TM",
    altCode: "TKM",
    numberCode: "795",
  },
  {
    name: "Turquia",
    code: "TR",
    altCode: "TUR",
    numberCode: "792",
  },
  {
    name: "Tuvalu",
    code: "TV",
    altCode: "TUV",
    numberCode: "798",
  },
  {
    name: "Ucrânia",
    code: "UA",
    altCode: "UKR",
    numberCode: "804",
  },
  {
    name: "Uganda",
    code: "UG",
    altCode: "UGA",
    numberCode: "800",
  },
  {
    name: "Uruguai",
    code: "UY",
    altCode: "URY",
    numberCode: "858",
  },
  {
    name: "Uzbequistão",
    code: "UZ",
    altCode: "UZB",
    numberCode: "860",
  },
  {
    name: "Vanuatu",
    code: "VU",
    altCode: "VUT",
    numberCode: "548",
  },
  {
    name: "Vaticano",
    code: "VA",
    altCode: "VAT",
    numberCode: "336",
  },
  {
    name: "Venezuela",
    code: "VE",
    altCode: "VEN",
    numberCode: "862",
  },
  {
    name: "Vietnã",
    code: "VN",
    altCode: "VNM",
    numberCode: "704",
  },
  {
    name: "Zâmbia",
    code: "ZM",
    altCode: "ZMB",
    numberCode: "894",
  },
  {
    name: "Zimbábue",
    code: "ZW",
    altCode: "ZWE",
    numberCode: "716",
  },
];
